In [1]:
import tensorflow as tf
from resnet_model import face_resnet_v2_generator

In [2]:
def _get_bn_vars(sess):
    "Return values of internal BatchNorm variables"
    beta = None
    gamma = None
    moving_mean = None
    moving_variance = None
    for v in tf.global_variables():
        if v.name == "batch_normalization/beta:0":
            beta = sess.run(v)
        elif v.name == "batch_normalization/gamma:0":
            gamma = sess.run(v)
        elif v.name == "batch_normalization/moving_mean:0":
            moving_mean = sess.run(v)
        elif v.name == "batch_normalization/moving_variance:0":
            moving_variance = sess.run(v)
    return beta, gamma, moving_mean, moving_variance

In [3]:
sess=tf.Session()

In [4]:
face_resnet=face_resnet_v2_generator(101,'channels_first')

In [5]:
image=tf.placeholder(tf.float32,shape=[None,64,64,3])
train_mode = tf.placeholder(tf.bool)
logits = face_resnet(image,train_mode)
global_step = tf.Variable(0,name='global_step',trainable=False)
init_op=tf.group(tf.global_variables_initializer(),tf.local_variables_initializer())
sess.run(init_op)

In [6]:
saver=tf.train.Saver()

In [7]:
beta, gamma, moving_mean, moving_variance = _get_bn_vars(sess)

In [8]:
print(beta)
print(gamma)
print(moving_mean)
print(moving_variance)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [9]:
ckpt = tf.train.get_checkpoint_state('./models/')
if ckpt and ckpt.model_checkpoint_path:
    saver.restore(sess,ckpt.model_checkpoint_path)

INFO:tensorflow:Restoring parameters from ./models/model.ckpt-1859


In [10]:
beta, gamma, moving_mean, moving_variance = _get_bn_vars(sess)
print(beta)
print(gamma)
print(moving_mean)
print(moving_variance)

[-0.0275517  -0.12395363 -0.01182774 -0.05015647  0.02828528 -0.03763871
 -0.044938    0.05675718  0.04511974  0.16343968 -0.03754145 -0.0369263
  0.08361129  0.14107491  0.12736066  0.10710721]
[ 1.03072608  0.91419107  1.00804102  0.92962807  1.1092279   0.95691186
  1.01474869  1.03356481  1.00812161  1.05629396  0.9949578   0.95793682
  1.01117671  1.13097143  1.04075575  1.06190968]
[-0.070938    0.12820145  0.05121474 -0.17679764  0.0125132  -0.17729104
  0.04007599  0.02694571 -0.06966765  0.00472474  0.06226692 -0.24019249
 -0.03199707  0.00554406  0.01333491  0.02972084]
[ 0.03124518  0.08889063  0.01743719  0.08315677  0.01345093  0.07824906
  0.04940155  0.01667738  0.02260081  0.01092163  0.1467156   0.34035856
  0.01930385  0.00908405  0.01453228  0.02594457]


In [11]:
sess.run(global_step)

1859